# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: numstore.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0enumstore.proto\x12\x08numstore\"+\n\rSetNumRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x03\"\x1f\n\x0eSetNumResponse\x12\r\n\x05total\x18\x01 \x01(\x03\"\x1a\n\x0b\x46\x61\x63tRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\"9\n\x0c\x46\x61\x63tResponse\x12\r\n\x05value\x18\x01 \x01(\x03\x12\x0b\n\x03hit\x18\x02 \x01(\x08\x12\r\n\x05\x65rror\x18\x03 \x01(\t2~\n\x08NumStore\x12;\n\x06SetNum\x12\x17.numstore.SetNumRequest\x1a\x18.numstore.SetNumResponse\x12\x35\n\x04\x46\x61\x63t\x12\x15.numstore.FactRequest\x1a\x16.numstore.FactResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'numstore_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SETNUMREQUEST']._serialized_start=28
  _globals['_SETNUMREQUEST']._serialized_end=71
  _globals['_SETNUMRESPONSE']._serialized_start=73
  _globals['_SETNUMRESPONSE']._serialized_end=104
  _globals['_FACTREQUEST']._serialized_start=106
  _globals['_FACTREQUEST']._serialized_end=132
  _globals['_FACTRESPONSE']._serialized_start=134
  _globals['_FACTRESPONSE']._serialized_end=191
  _globals['_NUMSTORE']._serialized_start=193
  _globals['_NUMSTORE']._serialized_end=319
# @@protoc_insertion_point(module_scope)
